### ISSUE TITLE
Wrong about

### ISSUE THREAD

**Issue by SajjadAemmi** [asefsoft/tv-alert#1]
Correct about:
Get notified whenever a new episode of your favorite TV series is released.

**Comment by asefsoft** [comment]
Thanks Sajjad
You mean using **Inform** is incorrect?
can you elaborate on that?

**Comment by SajjadAemmi** [comment]
Yes!
You implemented a very good software to send notifications to users.
The term **_notification_** is usually used in the field of technology.

**Comment by asefsoft** [comment]
yes I agree that notification is sounds more natural.
